# Generated by Django 4.2 on 2024-12-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='introduce',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
