# Generated by Django 4.2 on 2024-12-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='updated_at',
            new_name='last_login',
        ),
    ]
