# Generated by Django 4.2 on 2024-12-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='introduce',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
