# Generated by Django 4.2 on 2024-12-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='introduce',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
