# Generated by Django 4.2 on 2024-12-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_wish_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewCnt',
            field=models.IntegerField(default=0),
        ),
    ]
