# Generated by Django 4.2 on 2024-12-25 11:36

from django.db import migrations, models
import django.db.models.deletion
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_viewcnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='wish',
            name='unique_wish',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(storage=products.utils.OverwriteStorage(), upload_to=products.utils.rename_imagefile_to_pid),
        ),
        migrations.AddConstraint(
            model_name='wish',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_wish'),
        ),
        migrations.AddField(
            model_name='producthashtag',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.hashtag'),
        ),
        migrations.AddField(
            model_name='producthashtag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='hashtags',
            field=models.ManyToManyField(related_name='products', through='products.ProductHashtag', to='products.hashtag'),
        ),
        migrations.AddConstraint(
            model_name='producthashtag',
            constraint=models.UniqueConstraint(fields=('product', 'hashtag'), name='unique_product_hashtag'),
        ),
    ]
